Test the add_integer function
>>> add_integer(1, 2)
3

>>> add_integer(100.5, 2)
102

>>> add_integer(2)
100

>>> add_integer("Hello", 3)
Traceback (most recent call last):
...
TypeError: a must be an integer

>>> add_integer(4, "World")
Traceback (most recent call last):
...
TypeError: b must be an integer

